### ISSUE TITLE
The Tequila API related Issues.

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#116]
If you realize some issue related to Tequila API pls write it here.
From time to time we will summarize it and push to Tequila developers.

**PLS don't forget that is public so be aware of sensitive data!!!**

**Comment by FilipMessa** [comment]
I missing documentation for API response.
For example, when I call location API, I get an array of location, some fields are self-explanatory by their name, but there is a `type` field and I do not know how many types of values exists for it.

**Comment by FilipMessa** [comment]
Delays 
- This issue is touching the whole kiwi.com search API, it is related to the price verification, there is possible to speed it on BE but then we can't guarantee exact prices, but because the margarita is just example app maybe we can use this faster way.

**Comment by JoseDuSV** [comment]
**Search_api**
`route` - Naming should be updated according to glossary https://kiwi.wiki/kiwi/handbook/#/comms/glossary across endpoints. Instead of `route`, `segments` will be probably more suitable.

`route[x].carrier.name` - Carrier name is missing in response and only code is currently available. Should be added to unify response with other endpoints where this value is available.

`route[x].airline` - Unify carrier related props naming. `airline` inside `route` object should be renamed to `carrier` to unify it with `operating_carrier` which is also present on the same object.

**Comment by JoseDuSV** [comment]
**Booking_api**

`transfers` - Missing description, seems to be always just empty array.

`segments` - Missing description, seems to be always just empty array.

`route` - Missing description, confusing compared to `route` array in `search_api` with completely different content. Content is similar to `routes` from `search_api` but there are still inconsistencies. Search `routes` contains `[ "PRG", "FRA" ], [ "FRA", "PRG" ]` for return flight. But booking `route` is just `[ "PRG", "FRA" ]` for similar case, so I cannot distinguish if it’s one-way or return flight.

`flights` - Content and structure seems to be quite similar to `route` from `search_api`. Consider if naming and maybe even content can be unified. For example departure city is called `cityFrom` on one endpoint and `src_name` on second one.

`flights[x].airline` - It looks like data can be cleaned or description with differences should be added. For example repeating code value `VY` (for Vueling) is present as `code`, `iata`, `iatacode` and it can be confusing which one should be used.

**Comment by aalises** [comment]
**Search API**
The `search` endpoint with different `sort` parameter values does not work for all cases. So far `sort=price` and `sort=quality` work but `sort=duration` does not, the results are equivalent to the `price` sorting...

**Comment by JoseDuSV** [comment]
**Tequila website**

- `API documentation` link in [Resources](https://tequila.kiwi.com/portal/resources) section currently points to `Locations API` section. It should probably lead to some page with endpoints summary/description. Or it can be removed.
<img width="288" alt="Screenshot 2019-04-17 at 13 58 15" src="https://user-images.githubusercontent.com/2660330/56286011-e45e3780-6118-11e9-8a55-c31961feb8c7.png">

- There are browsable schemas at the bottom of some pages like on [Booking API](https://tequila.kiwi.com/portal/resources/booking_api). But they are missing on some other endpoints, for example on [Search API](https://tequila.kiwi.com/portal/resources/search_api). It should be unified.
<img width="250" alt="Screenshot 2019-04-17 at 14 02 01" src="https://user-images.githubusercontent.com/2660330/56286184-63ec0680-6119-11e9-9447-9dd4712bb8d6.png">

- There are links to some "non-kiwi" code samples in docs like https://gist.github.com/jBenes/32dd9b9120adf58381aa in **Booking API** description. There are also some old unanswered questions under this gist.
We should put all examples into some Tequila related repo under https://github.com/kiwicom .
<img width="518" alt="Screenshot 2019-04-17 at 14 06 35" src="https://user-images.githubusercontent.com/2660330/56286441-073d1b80-611a-11e9-83e8-73f86339b9e1.png">
