### ISSUE TITLE
Forbid to have departure date after the date of arrival

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#118]
Right now you can set the date of departure after the date of arrival. When you do it the app crashes.

![simulator screen shot - iphone x - 2019-01-14 at 14 38 08](https://user-images.githubusercontent.com/858321/51116038-33d75380-180a-11e9-8525-ef3b91cd7db2.png)
![simulator screen shot - iphone x - 2019-01-14 at 14 38 12](https://user-images.githubusercontent.com/858321/51116042-35088080-180a-11e9-971b-36fa79235ebd.png)

**Comment by JoseDuSV** [comment]
Closed by #119
