### ISSUE TITLE
Component: create the AddBaggage component

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#122]
Create the AddBaggage component.
This issue is subtask #73  

Todo:
- [ ] Add footer notes part
- [ ] Add tests https://github.com/kiwicom/margarita/pull/526#discussion_r265507786
- [ ] Make whole `BaggageBundle` component clickable https://github.com/kiwicom/margarita/pull/526#discussion_r266396855

**Comment by RobinCsl** [comment]
@FilipMessa I cannot see this anywhere in the designs now. Could you provide more context for this task, please?

**Comment by JoseDuSV** [comment]
@RobinCsl It seems like this part of design was recently changed and currently look like this:

<img width="399" alt="screenshot 2019-02-11 at 10 41 14" src="https://user-images.githubusercontent.com/2660330/52555299-9449b880-2de9-11e9-9d16-fb6ed0e4ce97.png">

https://www.figma.com/file/f2eLsS6JiJvLcuEiahbYU51Y/Bags-2.5

**Comment by FilipMessa** [comment]
As @JoseDuSV mentioned above, the design changed now it is a part of the passenger form.
https://www.figma.com/file/OUhBJ9rPaTbRljptC0lrRrUF/Multistep?node-id=1100%3A2333
