### ISSUE TITLE
On Android, the NetworkRequests are failing for some reason

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#130]

**Comment by RobinCsl** [comment]
@JoseDuSV found the answer:
> I just remembered the required port forwarding related to storybook on Android emulator ( https://github.com/storybooks/storybook/tree/next/app/react-native#start-app ). And it seems to be the same case with our failing fetch requests that we discussed yesterday.
After I tried `adb reverse tcp:4000 tcp:4000` everything works fine and results are properly loaded

So we should probably add this to the docs.

**Comment by FilipMessa** [comment]
Thanks
