### ISSUE TITLE
Update structure of ConnectionCard

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#151]
Waits for #123 

- [ ] Rename `ConnectionCard` to `ItineraryCard`
- [ ] Update structure of `ConnectionCard` in Universal components. Right now `ConnectionCard` has only `wayForth` and `wayBack` props, but for example, this is not universal if we want to use it for itineraries with more than two sectors (like Kiwi Nomad). Example:
    ```
    Prague - Eidhoven, Eidhoven - Oslo
    Oslo - Stockholm
    Stockholm - Prague
    ```

**Comment by FilipMessa** [comment]
@jvaclavik what is a state of this task?

**Comment by JoseDuSV** [comment]
@FilipMessa this one is complete, so we can close it.
