### ISSUE TITLE
Separate date/time formats to some config 

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#152]
It should not be in the screens or the components

**Comment by JoseDuSV** [comment]
We can probably use and extend `packages/utils/localization/DateFormatter`.

**Comment by FilipMessa** [comment]
@jvaclavik could you please be more specific about this issue? Is this still relevant?

**Comment by JoseDuSV** [comment]
@FilipMessa I think this one was solved by adding `@kiwicom/margarita-config` where we have `DAY_MONTH_DATE_FORMAT` and `HOURS_MINUTES_FORMAT`. So we can close this one.
