### ISSUE TITLE
Currency should not be set manually

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#153]
It should be probably based on locale of the device. But it's for discussion

Right now it's in in `Itinerariesloader.js`:

```
const params = {
    flyFrom: input.travelFrom,
    dateFrom: parseDate(input.dateFrom),
    dateTo: parseDate(input.dateFrom),
    to: input.travelTo ?? 'BCN', // Currently crashes without this fallback, fix hardcoding later, see https://skypicker.slack.com/archives/C7J2QM28G/p1544189402006200?thread_ts=1544188700.004300&cid=C7J2QM28G
    ...(input.returnDateFrom && {
      returnFrom: parseDate(input.returnDateFrom),
    }),
    ...(input.returnDateTo && {
      returnTo: parseDate(input.returnDateTo),
    }),
    ...(input.passengers && {
      adults: input.passengers.adults ?? 0,
      children: input.passengers.children ?? 0,
      infants: input.passengers.infants ?? 0,
    }),
    curr: 'EUR',
    limit: 10, // TODO pagination
  };
```

**Comment by JoseDuSV** [comment]
I think that default value can be based on device locale.
But maybe we should later add some way to change it, like in current mobile app (under Profile -> App Settings). By implementing some kind of basic Settings screen.

<img width="269" alt="screenshot 2019-01-25 at 13 59 40" src="https://user-images.githubusercontent.com/2660330/51747350-7c63fc00-20a9-11e9-83b6-c8cc265d09d0.png">
