### ISSUE TITLE
Improve initial rendering in web version

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/margarita#231]
Because of server-side rendering and layout responsivity handled by js we cannot set `layout` value of `LayoutContextProvider` inside constructor. 
Because different initial layout size value on server and front-end will cause `nextjs` content mismatch error during initial render.

Value is currently set inside `componentDidMount` of `LayoutContextProvider`. Which solves the issue but there is still ugly layout reshuffle during initial render which should be removed.

![layout-flicker](https://user-images.githubusercontent.com/2660330/52420778-0329c780-2af3-11e9-8d91-84bd777500c4.gif)

**Comment by tbergq** [comment]
Maybe we could show some loader/spinner until the dimensions have been calculated?

**Comment by JoseDuSV** [comment]
@tbergq As I think about it, spinner as in other cases should be ok. It will definitely improve experience. 

I've been also thinking about using `user-agent` info on server to set correct initial layout value. But this will probably work only for mobile, where phones can be detected quite accurately. But it will still be inaccurate for desktop, where browser window size can be totally random.

**Comment by RobinCsl** [comment]
Also, right now, bear in mind we are doing server-side rendering at build time, which I guess is more called pre-rendering. We are just serving static files. So loader sounds good to me.
