### ISSUE TITLE
Shouldn't be possible to search without locations

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#276]
This input:
![screenshot 2019-02-13 at 12 05 04](https://user-images.githubusercontent.com/858321/52707280-9d708c00-2f87-11e9-99e6-c7190508738f.png)

will produce this:
![screenshot 2019-02-13 at 12 05 36](https://user-images.githubusercontent.com/858321/52707307-b0835c00-2f87-11e9-907d-7e5b50e49842.png)

**Comment by JoseDuSV** [comment]
We talked about it with @FilipMessa and for now we will at least add some default values like `Praha` (or Brno?) -> `Anywhere`. So the case when inputs are empty shouldn't happen.

**Comment by RobinCsl** [comment]
Some form validation could be useful, but since we are going to use the placepicker eventually, I guess it's not so necessary?

**Comment by tbergq** [comment]
In current app, you get an alert if you try to search without inputing anything.

**Comment by tbergq** [comment]
![img_4946](https://user-images.githubusercontent.com/7705041/52708528-aca50900-2f8a-11e9-9962-a322506a4976.jpg)

**Comment by jvaclavik** [comment]
@tbergq And does it work for iOS simulator and web? Because I haven't seen this alert.

**Comment by RobinCsl** [comment]
@tbergq We could do something like that, yes.
@jvaclavik That's because that's the Kiwi.com app, not Margarita 😉
