### ISSUE TITLE
Create the GraphQL query for search flights (allFlights)

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#28]
#  allFlights query 

The first use will be in the search form. [design](https://drive.google.com/drive/u/1/folders/1FvfYLKao8F2IZ0F1bmEkowIxCjRr-hWs)

The `allFlights` query should handle the search for a flight. 
The query should accept these parameters:
1. from:  (type Location, required) 
2. to: (type Location, required) 
3. date:(type Date, required) 
4. returnDate: (type Date, optional) 
5. passengers: (type Passengers, optional with default value `adults=1`)

**Tequila API:** https://tequila.kiwi.com/portal/resources/search_api
**for inspiration:** https://github.com/kiwicom/graphql/blob/master/src/flight/queries/AllFlights.js

**Comment by michalsanger** [comment]
Let's wait how we decide about having input types for queries and mutations

**Comment by FilipMessa** [comment]
@michalsanger Did you mean this conversation? https://skypicker.slack.com/archives/C6C320B8V/p1543836545003500

**Comment by tbergq** [comment]
That link and article is it not more related to input types for mutations?

On a general basis, I would think of it as a function. Should I add a parameter to the function, or should it take an object as parameter?

If there is just one value say an id, it does not make that much sense to wrap it into an object does it? On the other hand, if I pass 5 parameters, it might be better to create an inputtype

@FilipMessa @michalsanger
