### ISSUE TITLE
Document: Git Commit Message Convention

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#33]

**Comment by FilipMessa** [comment]
should be similar to https://github.com/kiwicom/universal-components/blob/aa4fba62c19c9fd7f92c3d15edc6b514dba994d9/CONTRIBUTING.md

**Comment by RobinCsl** [comment]
This issue is even more relevant now, since we have integrated `universal-components`: how do we generate nice changelogs from commit messages if everything is mixed together, etc.
