### ISSUE TITLE
SearchContext initialised on every navigation to /

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/margarita#350]
I don't know if that's a feature, but as a user, I would expect that by going back to the home screen from the results page, I would see the same locations I used as search params.

This is because SearchContext is initialised whenever we navigate to the home page, so we lose previous state by going back.

**Comment by tbergq** [comment]
I suppose this is for web only?

Go to kiwi.com, search, click the back button in the browser. Your search is lost. I think this is quite normal on web.

**Comment by RobinCsl** [comment]
Fair enough. I guess I would not want to reconfigure dates, etc. But we can leave as it is for now since the same behaviour happens on kiwi.com. Thanks!
