### ISSUE TITLE
Create empty ResultDetail screen

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#366]
https://www.figma.com/file/OUhBJ9rPaTbRljptC0lrRrUF/Multistep?node-id=8%3A6

**Comment by JoseDuSV** [comment]
I think we already have the issues for this one. Top part #72 will be mostly reused from MMB.
And #73 for passenger related part, this one probably just needs to be slightly updated according to current designs.

**Comment by jvaclavik** [comment]
> I think we already have the issues for this one. Top part #72 will be mostly reused from MMB.
> And #73 for passenger related part, this one probably just needs to be slightly updated according to current designs.

Yes, but this issue should be mainly for creating empty screen and connect it with the ResultsScreen (I need it for another PR).
