### ISSUE TITLE
Add @kiwicom/graphql-bc-checker

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#40]
https://github.com/cap-collectif/graphql-doctor

**Comment by FilipMessa** [comment]
Another nice alternative https://medium.com/the-guild/graphql-inspector-481c1a5ef616?_branch_match_id=491570299227905716

**Comment by michalsanger** [comment]
For BC breaks check, did you consider this? 
https://www.npmjs.com/package/@kiwicom/graphql-bc-checker

**Comment by FilipMessa** [comment]
Sure, why not? I just some fancy stuff there but make sense us our own solution and improved it if we need or want.

But in the current state, we don't need to add this because we are the only customer, yet.
