### ISSUE TITLE
Landing Page is not displayed properly on the moment its opened

### ISSUE THREAD

**Issue by KarinaDavtyan** [kiwicom/margarita#422]
Its around a second for desktop and a bit longer for mobile, but at least its not happening on every refresh

<img width="611" alt="screenshot 2019-02-27 at 13 49 18" src="https://user-images.githubusercontent.com/25099820/53491366-85742e80-3a96-11e9-913b-9a7b91f612b9.png">

**Comment by JoseDuSV** [comment]
@KarinaDavtyan Can we close this one? It seems that problem was related to Gatsby.

**Comment by KarinaDavtyan** [comment]
> @KarinaDavtyan Can we close this one? It seems that problem was related to Gatsby.

I think we shouldnt do it just yet because yes now its much better and styles are loaded. But its still blinking and I guess its happening due to passing `align` props which depend on the `window`. I wanted to fix it in the next PR

**Comment by KarinaDavtyan** [comment]
@JoseDuSV well, I am not sure about this anymore because it seems that once deployed to gh-pages its just broken without any blinking
