### ISSUE TITLE
Docs: Create base outlines for the documentation

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#445]

**Comment by michalsanger** [comment]
My idea is to have topics grouped by two roles of our "users"

**First-time visitor**
- What is this all about?
- Where can I see the web and mobile demo?
- Supported features, roadmap
- What is Tequila API?
- Technical big picture overview

**Developer**
- How to install, run and build?
- What Env vars to set?
- Where to ask for help?
- Folder structure
- Technical overview for web and mobile
- Components documentation
