### ISSUE TITLE
Create circled Button

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/margarita#465]
Opened by @jvaclavik 

![](https://user-images.githubusercontent.com/858321/53562425-a188d600-3b51-11e9-86c7-ebfa084ed304.png)

(Original issue https://github.com/kiwicom/universal-components/issues/257)

**Comment by jvaclavik** [comment]
Done: https://github.com/kiwicom/universal-components/pull/261

(working also in Margarita)
