### ISSUE TITLE
It's not possible to create bold Text

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#479]
It doesn't work on iOS. 
It's not possible to use prop (`<Text weight="bold">...</Text>`) nor style (`fontWeight: "bold"`)

**Comment by JoseDuSV** [comment]
It is related to this one https://github.com/kiwicom/margarita/issues/466
@jvaclavik For now you can at least use extended `Text` component from `margarita-components`.

**Comment by jvaclavik** [comment]
I see, sorry. Closing
