### ISSUE TITLE
BUG: TagsInput - The input filed width don't correspond to character length on Safari 

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#509]
**Describe the bug**
**TagsInput** component:
The input filed width don't correspond to character length on Safari 

**To Reproduce**
1. run storybook
2. open the TagsInput
3. write down long text

**Screenshots**
It contains Bratislava word.

<img width="1274" alt="screen shot 2019-03-08 at 14 04 07" src="https://user-images.githubusercontent.com/6354326/54030283-63bc2b00-41ab-11e9-822f-b0cfcb23e2a7.png">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: Safari
 - Version: 12.0.2

**Comment by aalises** [comment]
@FilipMessa Seems related to the `onLayout` callback not being fired on Safari in the `InputField` component
