### ISSUE TITLE
Implement confirm_payment from Booking API

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/margarita#537]
Tequila Booking API `confirm_payment` request confirms that the user payment for booking was successful.
Booking needs to be saved first by `save_booking` request ( related issue #536 ).

Implementation will depend on how we decide to mock payment flow for now.
Before starting on this issue we should discuss with Tequila team current state of `Payments API`. So we can mock payments flow to be easily replaced/updated once Payments API is ready.

Booking API documentation:
https://tequila.kiwi.com/portal/resources/booking_api
https://tequila.kiwi.com/portal/resources/booking_and_payment_flow

**Comment by aalises** [comment]
Schema proposal. In this case it's pretty simple.

**Mutation name (POST):**
```
confirmPayment
```

**Payload**
```
type ConfirmPaymentPayload {
  bookingID: String
  transactionID: String!
}
``` 

**Output**
```
type ConfirmPaymentResponse {
  status: Int!
  price: Float!
}
```
@JoseDuSV
