### ISSUE TITLE
Docs: Prepare Supported features and Roadmap 

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#539]
Prepare text for the margarita docs, with the topic "Prepare Supported features and Roadmap"

It should be lived here: http://localhost:1337/margarita/docs/features-roadmap

**Comment by JoseDuSV** [comment]
@FilipMessa Do we have any clear roadmap? If not, what about just renaming this section to `Features` for now and change `Roadmap` to something like `Planned features` where we can mention Multicity, Nomad (+ some other possible features).

**Comment by FilipMessa** [comment]
@JoseDuSV Yes, this is a good idea, we should reconsider what topics make sense and keep it simple as possible.
