### ISSUE TITLE
Docs: Technical Big Picture 

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#541]
Prepare text for the margarita docs, with the topic "Technical Big Picture"
It should be lived here: http://localhost:1337/margarita/docs/technical-big-picture

**Comment by JoseDuSV** [comment]
@FilipMessa What should be the difference between this section and https://github.com/kiwicom/margarita/issues/544 ? Cannot we just merge it and mention `Write Once, Render Anywhere` approach just in header of `Technical-overview`?

**Comment by FilipMessa** [comment]
I like your point, let's do it as you suggest. THNKS 💯
