### ISSUE TITLE
Create the new search itineraries queries.

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#556]
Create the two new queries for search itineraries.
In the margarita app we currently have `searchItineraries` query for searching itineraries.
The `searchItineraries` query accept the `ItinerariesSearchInput` which schema looks like this
```
travelFrom: [String]
travelTo: [String]
dateFrom: Date!
dateTo: Date
returnDateFrom: Date
passengers: PassengerInputs  
```
This input allows a search for **one-way** and also for the **return** type of itineraries. But it is confusing what field you need to be filled for oneway and what is required for return. And also is hard to extend this query, in future will be added multipcity and nomad. So one query for all type of search will change to mass, it will be hard to know what should be filled for when.

Because that looks like a better approach will create a standalone query for every type of search. It will easy to extend it and manage in the future.

Prepare the two searching queries base on the search type, the `searchOnewayItineraries` for oneway and the `SearchReturnItineraries` for return.

the schema design proposal:
```
input DateRangeInput {
	start: Date
	end: Date
  }

  enum SortSearchInput {
    PRICE
    DURATION
    QUALITY
    DATE 
  }

 enum OrderSearchInput {
   ASC
   DESC
 }

input LocationItineraryInput {
  slug: [String]
  ids:  [String] // It should be GlobalIDs not locationIds
 }

input ItineraryOneWayInput {
  origin:  LocationItineraryInput
  destination:  LocationItineraryInput
  outboundDate: DateRangeInput
}

input SearchOnewayInput {
  order: OrderSearchInput
  sort: SortSearchInput
  itinerary: ItineraryOnewayInput
  passengers: PassengersInput // schema already implemented
}

input ItineraryReturnInput {
  origin:  LocationItineraryInput
  destination: LocationItineraryInput
  outboundDate: DateRangeDate
  inboundDate: DateRangeInput
}

input SearchReturnInput {
  order: OrderSearchInput
  sort:  SortSearchInput
  itinerary: ItineraryReturnInput
  passengers: PassengersInput // schema already implemented
}

```

Tequila API docs: https://tequila.kiwi.com/portal/resources/search_api

PS: Don't try to do it in one PR, at least split it into two, one for `searchOnewayItineraries` and one for the `searchReturnItineraries`

**Comment by tbergq** [comment]
I consider it to be a greater mess when we now need add refetch containers for sorting. This means one component for query and one component for refetch pr type. 

Meaning we will end up with 8 components, (query for oneWay, return, multicity, nomad, then refetch container for the same) instead of just 2 components.

**Comment by tbergq** [comment]
If the reason for this is confusion about input, what about having 4 input types with different validations, one for each search type?
