### ISSUE TITLE
Check and Improve babel monorepo configuration

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#560]
Check our babel configuration, currently, we have installed the `@kiwicom/babel-preset-kiwicom` as a dependency but it looks like we don't use it anywhere.

**Comment by tbergq** [comment]
`@kiwicom/babel-preset-kiwicom` Is now being used in graphql. We could probably use it in other apps as well. Also, we could probably benefit from more funcionality from `@kiwicom/monorepo` package.

**Comment by tbergq** [comment]
Tests are now being run with `@kiwicom/monorepo` -> `monorepo-run-tests` 
#638
