### ISSUE TITLE
Fix styling for web in ResultDetailScreen

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#561]
**Describe the bug**
- Update styling of `ResultDetailScreen` (it's too wide)
- using `maxWidth` constants in `PaymentScreen`

**Comment by FilipMessa** [comment]
What about set also some max width for `/result-detail` page?

**Comment by jvaclavik** [comment]
> What about set also some max width for `/result-detail` page?

Yes it's included 👍
