### ISSUE TITLE
Add styling options for Button

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/margarita#588]
**Is your feature request related to a problem? Please describe.**
We would need to modify the borderRadius of the Button component.

**Describe the solution you'd like**
I see different solutions: either we provide some ThemeProvider using orbit-design-tokens as default values (that's probably what orbit guys are doing?), so that anyone could override these values with their custom theme. 
Or the easy, short-term solution is to add a prop to Button to allow styling the container. (I believe ButtonInner should be modified)

In another project, we need borderRadius 3 for the Button, which corresponds to `defaultTokens.borderRadiusNormal`.

**Comment by JoseDuSV** [comment]
I definitely prefer to be able to override styles using just `ThemeProvider`. It will be probably cleaner than using some custom Button wrapper implementation (to prevent setting `borderRadiusNormal` for each button) inside other projects.

There is only small issue similar to one we faced with text theming. Button is quite frequent component so it will be good to avoid generating styles with theme value on every render.
But in can be solved like in case of `Text` by simply generating some style like `buttonBorderRadius` inside theme provider. 
With this we will start implementing something close to atomic css for RN. If we decide to go this way I would like to do some quick research, just to be sure how RN handles multiple style values in style prop array compared to using dynamic styles inside render function.

**Comment by aalises** [comment]
Fixed by adding a `style` prop to the `Button` on #626

**Comment by d4n1b** [comment]
Hi! Awesome UI library : )
Is there any roadmap to allow customisation of components directly from `ThemeProvider`?

Cheers!

**Comment by RobinCsl** [comment]
Hi @d4n1b,
Thanks for your interest, it's always nice to hear about! 
To be completely honest with you, this UI library is not under active development at the moment. That being said, since it's open source, we would gladly accept contributions. 😉 

There are quite a few things that would need doing to make Universal Components great again:
- ship only the React Native code as NPM package and give instructions on how to include it into a web project by modifying Webpack config for example;
- improve capabilities of `ThemeProvider`;
- contribute to https://github.com/ptomasroos/react-native-multi-slider to remove dependency on our fork of it;
- clean the dependency tree of the library (right now for example, `@storyook/react-native` is a dependency, which it shouldn't be...);
- and more...

Would you be interested in participating?
