### ISSUE TITLE
Reduce overdraw

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#593]
We should optimise overdraw in the app. 

For more info see https://launchdrawer.com/i-made-react-native-fast-you-can-too-9e61c951ce0 and https://www.youtube.com/watch?v=T52v50r-JfE

<img width="272" alt="Screenshot 2019-03-25 at 17 44 07" src="https://user-images.githubusercontent.com/858321/54992120-c7719100-4fbe-11e9-8bd6-62a9fa416636.png">

**Comment by tbergq** [comment]
Because of the nature of react-native, I am not sure we are able to improve this very much. 

Performance optimisations should be done if/when something is slow. The app runs fine for now AFAIK.
