### ISSUE TITLE
Provide CHANGELOG

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/margarita#595]
**Is your feature request related to a problem? Please describe.**
When upgrading versions of `universal-components`, like on https://github.com/kiwicom/mobile, it comes as a surprise if there were API/breaking changes.

**Describe the solution you'd like**
We would need to create a CHANGELOG file for each version. I believe there is an explanation of how that should work on the incubator monorepo wiki page. We can discuss it here I believe.
That would mean for instance that every PR changing the API in some way will need to provide a description in that CHANGELOG file.

**Comment by RobinCsl** [comment]
@vepor How do you manage that in https://github.com/kiwicom/orbit-components?

**Comment by vepor** [comment]
Manually now. We have a document with all changes.
