### ISSUE TITLE
[Button] Remove 'sublabel' prop

### ISSUE THREAD

**Issue by KarinaDavtyan** [kiwicom/margarita#609]
`Sublabel` prop is not used anywhere in margarita so we could remove it

**Comment by RobinCsl** [comment]
@tbergq Is it used in https://github.com/kiwicom/mobile by any chance?

@KarinaDavtyan Since we released this library, I don't think we should remove props like that.

**Comment by JoseDuSV** [comment]
I'm thinking what was our original use-case for it. Cannot find anything in designs. And only this note can be found in original repo https://github.com/kiwicom/universal-components/pull/30 which doesn't tell much about its purpose.
I'm also not sure why it is available only for mobile.

As @RobinCsl note, it can be tricky to remove props like this. But in this case I don't think it is a will be used anywhere. And if so, it's kind of special case which can be solved by passing custom labels component as `label` prop.

**Comment by tbergq** [comment]
Nope, sublabel is not used in mobile repo
