### ISSUE TITLE
Consolidate naming of oneway, OneWay, oneWay

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#615]
I noticed that we are mixing up some naming (`OneWay`, `oneway`, `oneWay`). We should keep it consistent. I'm just not sure which form would be the best one.

<img width="479" alt="Screenshot 2019-04-02 at 11 21 47" src="https://user-images.githubusercontent.com/858321/55391517-d06fde80-5539-11e9-999f-beee0cefc561.png">
<img width="482" alt="Screenshot 2019-04-02 at 11 21 32" src="https://user-images.githubusercontent.com/858321/55391518-d1087500-5539-11e9-85ff-ee1c75dfa40d.png">
<img width="481" alt="Screenshot 2019-04-02 at 11 21 15" src="https://user-images.githubusercontent.com/858321/55391520-d1087500-5539-11e9-8b5c-d226303c91b5.png">

Similar problem is also with `return` and `Return`

**Comment by aalises** [comment]
@jvaclavik I think `Return` and `OneWay` are the ones that sound best to me, WDYT?

**Comment by JoseDuSV** [comment]
Good catch! Problem is that I'm quite ok with all variants :) So I just let others to decide. Maybe we can also consider `OW` and `RT` from glossary https://kiwi.wiki/kiwi/handbook/#/comms/glossary?id=r , but there is nothing for MultiCity and Nomad.
