### ISSUE TITLE
Revise @kiwicom/margarita-utils

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/margarita#619]
Revise `@kiwicom/margarita-utils` package content.

- [x] **Unify folders structure** - Currently we have few utils folders directly in package root and other few nested inside `src` and `helpers` subfolders. Maybe everything can be in root. Or we can use some logical subfolders like `formatters`, `constants`, `context`...

- [x] **Unify files naming** - We are mixing capital and small letters in file naming. For example: `device/Device.js` versus `helpers/capitalize.js` 

- [x] **Remove unused utils** - Check if all utils are actually used anywhere and remove unused. For example there are multiple formatters inside `localization` folder which we moved from https://github.com/kiwicom/mobile , but we have started using `date-fns` for date formatting, so we should consider if it still makes sense to keep it there.

**Comment by aalises** [comment]
Done on #623

**Comment by JoseDuSV** [comment]
Closed by #623
