### ISSUE TITLE
Implement gestures in RangeDatePicker

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#640]
Modifying date range should be possible to do with gestures like on http://kiwi.com.

- [x] iOS
- [x] Web
- [ ] Android

**Comment by jvaclavik** [comment]
Unfortunately for now we are not able to archive gestures on android because of this: https://github.com/kmagiera/react-native-gesture-handler/issues/139

**Comment by JoseDuSV** [comment]
> Unfortunately for now we are not able to archive gestures on android because of this: [kmagiera/react-native-gesture-handler#139](https://github.com/kmagiera/react-native-gesture-handler/issues/139)

And cannot we try some other library or try to improve current one?
I think that this component is quite important and we want to use it even in other projects, so it will be nice to make it work on Android. 
I'm just slightly worried that this issue is one year old and it's hard to tell if or when it will be really solved.

**Comment by jvaclavik** [comment]
> > Unfortunately for now we are not able to archive gestures on android because of this: [kmagiera/react-native-gesture-handler#139](https://github.com/kmagiera/react-native-gesture-handler/issues/139)
> 
> And cannot we try some other library or try to improve current one?
> I think that this component is quite important and we want to use it even in other projects, so it will be nice to make it work on Android.
> I'm just slightly worried that this issue is one year old and it's hard to tell if or when it will be really solved.

We could try to use different library but I'm not sure if it's problem of the library or Modal itself. 
(btw there are more problems with Android Modal, for example when you refresh app and modal is open, your app is stucked) 

What can we do is try to use JS based modal at least for Android. What do you think?
