### ISSUE TITLE
Scrollbar interferes with usability of RangeDatePicker

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/margarita#660]
**Describe the bug**
Scrollbar interferes with usability of RangeDatePicker, cf. attached screenshot.

This is on Chrome, Desktop.

**Screenshots**
<img width="410" alt="Screenshot 2019-04-12 at 12 47 22" src="https://user-images.githubusercontent.com/22741774/56032040-5ac9f680-5d21-11e9-8bd1-e1fe00873732.png">

**Comment by tbergq** [comment]
This might be more of a modal problem 🤔 

But when modal.height > window.height, and I scroll down to see ok and cancel button, the modal blur background is not covering bottom part of screen

![Screenshot 2019-04-15 at 11 13 02](https://user-images.githubusercontent.com/7705041/56120945-775b6e00-5f6f-11e9-8a39-87f294ebcc7b.png)

**Comment by RobinCsl** [comment]
Yes, I think it's a different issue. Could you please create one for it as well?

**Comment by tbergq** [comment]
Will do
