### ISSUE TITLE
Feature: Refactor search form into a separate component, add it to results page.

### ISSUE THREAD

**Issue by aalises** [kiwicom/margarita#674]
Currently the search form

<img width="722" alt="Screenshot 2019-04-15 at 15 17 40" src="https://user-images.githubusercontent.com/11021461/56135722-a2ef5000-5f91-11e9-942b-9848196ef713.png">

Is embedded into the search page. The idea is to reuse that component to also include it on the results page instead of the badges showing the itinerary:

<img width="370" alt="Screenshot 2019-04-15 at 15 21 27" src="https://user-images.githubusercontent.com/11021461/56136017-2f9a0e00-5f92-11e9-95f0-ae8f0697ac23.png">

By doing so, the user does not have to go back to do another search. To achieve it, refactoring the form into a separate component is required.

WDYT: @jvaclavik @RobinCsl @tbergq @michalsanger @FilipMessa @KarinaDavtyan @JoseDuSV

**Comment by jvaclavik** [comment]
I think it's a very good idea to improve UX of this element in Result screen, but I'm not sure if we want to repeat whole search form there. It could look fine on desktop, but probably not very well on mobile device.

I would suggest to redesign component `SearchParamsSummary` a bit and add possibility of picking the date directly from Result screen:

<img width="370" alt="56136017-2f9a0e00-5f92-11e9-95f0-ae8f0697ac23" src="https://user-images.githubusercontent.com/858321/56137676-a684d600-5f95-11e9-9dc0-025a0e75c1ad.png">

What do you think?

**Comment by tbergq** [comment]
I think we should replace the ugly header on web with the search form, but in mobile keep the current header.

**Comment by aalises** [comment]
I think that would be cool @tbergq . @jvaclavik the modal approach would also work for mobile but in terms of UX it is maybe not that clear that these can be edited or changed...

**Comment by tbergq** [comment]
@jvaclavik, what you suggest with changing dates by clicking on the date buttons is actually how the kiwi native app works, so yes, we should also implement that feature for rn-app 😊

**Comment by JoseDuSV** [comment]
+1 For search form above results on web and current header on mobile (with clickable dates).

**Comment by aalises** [comment]
Fixed on #677
