### ISSUE TITLE
Search filter options are cut on mobile

### ISSUE THREAD

**Issue by KarinaDavtyan** [kiwicom/margarita#678]
![Image from iOS (3)](https://user-images.githubusercontent.com/25099820/56206325-63d20500-604c-11e9-846e-80e8c68b79ac.png)

 - Device:  iPhone6

**Comment by aalises** [comment]
Yes, the component is only for `web` right now. We need to do another one, as discussed with @FilipMessa for `mobile` with a different design (vertical tabs maybe). @KarinaDavtyan 👀

**Comment by KarinaDavtyan** [comment]
So should we remove it for now from mobile? @aalises

**Comment by aalises** [comment]
Or we could modify the component to just `flex-direction: column` on mobile for now. PRs welcome 👍

**Comment by JoseDuSV** [comment]
Filters are hidden into small "badges" in current mobile app and on new designs https://www.figma.com/file/BiZpzn612rlJ85vAozQkRtwC/Results-Listing?node-id=5292%3A57080
Filter menu is then displayed inside modal after tapping on them.

But I don't think there is a plan to implement other/more filter options to Margarita. So we probably don't need to strictly follow designs for now and just some minimalistic version of what we already have can be ok.
