### ISSUE TITLE
Enhance SearchContext and Navigation functionality

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/margarita#682]
Url in **web** version should reflect changes in search parameters on results related pages like `results` and `result-detail`. Basically url should just reflect `SearchContext` props. 

The idea is that we should use just single _“source of truth”_ for screens related to search params (`index`, `results`, `result-detail`).
Currently we are mixing data from `SearchContext` and params from url/navigation. Which is not always clear and causes problems when we for example need to use types like `string | number` for some parameters.

One solution can be to use `SearchContext` for storing and providing all props. And on web just update and parse parameters from url (to `SearchContext`) on redirect or refresh.

We should also consider moving `SearchContext` to `_app.js` for **web** version to make structure equal to mobile, instead of defining it separately inside each page.

**Comment by aalises** [comment]
Closed on #686
