### ISSUE TITLE
Trip detail

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/margarita#70]
After taping on a connection in the list of results, a detail of the connect will appear. Unlike in the kiwi.com app and the design in Figma, it should open on a new screen (this will make the optimization for web easier).

Design: https://www.figma.com/file/XD9kQTOJxaqviaxD0g3AhAXS/Booking-Detail?node-id=0%3A1

The Close button on the bottom of the screen will be replaced by Back button in the main bar: the user can go back to the results using this new button. The "Book for xxxx" button will be the main CTA.

Also, there would be no Share button.

![image from ios](https://user-images.githubusercontent.com/7661448/50081214-2f5d5200-01ee-11e9-863c-708a8967b78b.png)

**Comment by FilipMessa** [comment]
related to https://github.com/kiwicom/universal-components/issues/138  and https://github.com/kiwicom/universal-components/issues/137

**Comment by JoseDuSV** [comment]
Closed by #433
