### ISSUE TITLE
Replace deprecated Hoverable components with new withHover HOC

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/margarita#718]
Implement new `hover` handling approach to remove all deprecation warnings from console, by replacing all `Hoverable` component implementations with new `withHover` HOC.

**Comment by aalises** [comment]
Can we get rid of `Hoverable` then?

**Comment by tbergq** [comment]
No, you don't need a custom function in NavbarLink. 

Just do this: 
```
render() {
    const activeOrHoverd = this.state.active || this.props.isHovered;
    return (
      <Hoverable
        onMouseEnter={this.onMouseEnter}
        onMouseLeave={this.onMouseLeave}
      >
        <TouchableWithoutFeedback onPress={this.onPress}>
          <View style={styles.container}>
            <Text
              size="small"
              type="primary"
              style={[styles.label, activeOrHoverd && styles.activeLabel]}
            >
              {this.props.label}
            </Text>
          </View>
        </TouchableWithoutFeedback>
      </Hoverable>
    );
  }
```

**Comment by JoseDuSV** [comment]
@aalises I think we can remove `Hoverable` after this. But I'll suggest to do it in separate PR, to make it more visible in commits history, so we can make it clear in next `universal-components` release.

**Comment by tbergq** [comment]
Yes, that was the idea, since it add 0 value.
