### ISSUE TITLE
Booking screen: Connection component

### ISSUE THREAD

**Issue by MRTNKCR** [kiwicom/margarita#72]
The connection (or flight - but we do also offer rides now :-) ) component offers a basic overview of the trip.

There would be no photo and no Share button.

<img width="533" alt="snimek obrazovky 2018-12-17 v 11 32 42" src="https://user-images.githubusercontent.com/7661448/50082636-bb24ad80-01f1-11e9-8792-5a441f0fdd70.png">

When open, the component should display the trip's details - this can be recycled from the Trip detail screen.

![image from ios](https://user-images.githubusercontent.com/7661448/50082685-d68fb880-01f1-11e9-93de-5b66a1e3ded0.png)

Design in Figma: https://www.figma.com/file/OUhBJ9rPaTbRljptC0lrRrUF/Booking?node-id=5%3A439

**Comment by FilipMessa** [comment]
done
