### ISSUE TITLE
Deployed version of graphql server still does not return gzipped content

### ISSUE THREAD

**Issue by tbergq** [kiwicom/margarita#727]

**Comment by aalises** [comment]
I think this has to be activated in AWS (there is the option in API Gateway https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-enable-compression.html#api-gateway-supported-content-encodings) and then enable it for serverless with `serverless-content-encoding` plugin (https://www.npmjs.com/package/serverless-content-encoding)

**Comment by aalises** [comment]
<img width="242" alt="Screenshot 2019-05-13 at 15 21 32" src="https://user-images.githubusercontent.com/11021461/57624731-d8885880-7592-11e9-94a9-f173500d233f.png">
