### ISSUE TITLE
Whole web results page should be scrollable in mobile resolution

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/margarita#732]
Search form currently fills almost whole screen and there is just tiny scrollable space for results (highlighted in green on screenshot).
![Screenshot_20190502-115709](https://user-images.githubusercontent.com/2660330/57068685-c37a1280-6cd2-11e9-99f8-98abae131c52.png)

Possible solution: Set fixed position just to header (or maybe also hide it after you scroll down) and make whole screen including search form scrollable.

**Comment by aalises** [comment]
We could also make the search form collapsed by default (e.g on a Dropdown with a `Show Search Form` label) on mobile resolutions @JoseDuSV

**Comment by JoseDuSV** [comment]
@aalises That can definitely also be the solution and probably less 'destructive' one. 
But personally I prefer to have whole page scrollable, basically like current kiwi.com implementation of mobile web.
It can be achieved quite easily, just by setting `overflowY: 'auto'` inside `web/components/layout` and disabling `flex: 1` style inside `web/components/results`. We just need to be sure that it will not cause any problems later and that we don't get lost in all the layout conditions.

![scroll-example](https://user-images.githubusercontent.com/2660330/57078801-3f825380-6cef-11e9-9821-07073be7fea5.gif)

**Comment by aalises** [comment]
The problem with the above approach is that on loading, the background color is not fully covered... we could set the flex on loading and then remove it when the data is loaded @JoseDuSV ?

**Comment by JoseDuSV** [comment]
True. Setting flex to fill whole height during loading will definitely makes sense.

**Comment by JoseDuSV** [comment]
While exploring it more deeper I think that this issue will be slightly bigger.
It is not related only to mobile, but we should include inputs and filters in scrollable wrapper even on desktop and basically copy kiwi.com results page behaviour.
Because if we try to open current results on most common user resolution or tablet, static content with inputs and filters will cover more than one third of screen space, which is not really necessary, because you don't really need them when you start browsing the results.

<img width="1357" alt="Screenshot 2019-05-03 at 11 53 49" src="https://user-images.githubusercontent.com/2660330/57131302-46b36b00-6d9c-11e9-8e4e-26d25939d28e.png">
