### ISSUE TITLE
Date input field should not be on two lines in Search screen

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#736]
There should be probably three dots (or cropped content?):

<img width="1110" alt="Screenshot 2019-05-03 at 08 55 59" src="https://user-images.githubusercontent.com/858321/57123231-638e7500-6d81-11e9-8382-d5e11c53ba3a.png">

How it works on kiwi.com:
<img width="1265" alt="Screenshot 2019-05-03 at 08 59 50" src="https://user-images.githubusercontent.com/858321/57123390-ec0d1580-6d81-11e9-9c01-d30450177e6f.png">

**Comment by JoseDuSV** [comment]
In this case I'll be slightly more for **crop** , with dots we will lose even more informations.
For me it's better to see at least `Thu 23 Ma` than `Thu 23 ...`.
