### ISSUE TITLE
Add limit parameter on Search API

### ISSUE THREAD

**Issue by aalises** [kiwicom/margarita#746]
**Is your feature request related to a problem? Please describe.**

From PR https://github.com/kiwicom/margarita/pull/735 , some performance problems arise when loading way too many results on screen and the body is scrollable (e.g on resizing the windows) on web version with mobile resolution.

**Describe the solution you'd like**

For solving it, we should consider implementing a sensible `limit` parameter on the search API call, for example, 50 results.

cc  @JoseDuSV

**Comment by JoseDuSV** [comment]
Just a quick idea. Cannot we actually change `results` screen structure a bit and use `ListHeaderComponent` prop of `FlatList` to keep current behaviour even on mobile?
By this we will make whole header (search form + filters) part of the `FlatList` so we can keep current behaviour when results are added during scroll and we don't need to limit their number.

![scroll-header-sample](https://user-images.githubusercontent.com/2660330/57215195-72c52b00-6fec-11e9-8d39-99f947ecf7da.gif)

**Comment by aalises** [comment]
@JoseDuSV We considered it when I was first doing the `SortTabs`. The problem is that it would be part of the list and not be kept on reload :( (disappeared when the list was loading)

**Comment by JoseDuSV** [comment]
True, but we should now reconsider if disappearing sort tabs aren't actually better than limiting number of results.
In short, I'm ok with limited results for now. But I treat it like a temporary solution and we should improve this part later. It can be by pagination/load more or structure update. Basically we should create new issue and mention that results are now limited (+ why) to not forget that this part should be improved.

**Comment by aalises** [comment]
Yep! I think the pagination is quite necessary and the best solution but it's still not implemented in Tequila AFAIK

**Comment by FilipMessa** [comment]
@aalises Do you have some information from Tequila devs, about the plan to implement the pagination?
