### ISSUE TITLE
Broken the FilterTabs position in the layout.

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#764]
Fix offset on the left corner

![bug-visual-tabs](https://user-images.githubusercontent.com/6354326/57621667-5432d700-758c-11e9-8af7-0d22d4f4ce3c.gif)

**Comment by aalises** [comment]
How can I reproduce this? it looks good on Chrome from the Macbook.

**Comment by FilipMessa** [comment]
I also using  Chrome for the MacBook, and I have this bug there. What resolution you have?

**Comment by aalises** [comment]
*13,3-inch (2560 x 1600)* 👀
