### ISSUE TITLE
ResultPage: The new search should be done after the user clicks the search button.

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#769]
When a user change location, destination or origin new request for the result is sent to the server immediately. 

Right behavior should be, that new request should be sent od server after a user clicks on the search button in the search form.

![searchform](https://user-images.githubusercontent.com/6354326/57681622-58183500-7630-11e9-94d0-23b420a96e5a.gif)

**Comment by aalises** [comment]
@FilipMessa This would be a major refactoring and was discussed some weeks ago with @tbergq and @JoseDuSV .The point is that now all the components are connected to the `SearchContext` which causes the rerender of all the consumers on change, also triggering the search. This is the way it also works on `Kiwi.com`... It was decided to keep it like that at the moment.

To achieve what you say, we would have to decouple all the components from the context and store all the values on a model on the `SearchForm` and set the form state to the context all at once on search (after validation, whatever), which IMO would be better architecturally wise but a major refactor which I don't know if we want

**Comment by FilipMessa** [comment]
Do you have estimation how long will be this take?

There is still option two that we will just hide button on this page.

**Comment by aalises** [comment]
Hmmm 3 days to be sure, cannot tell... But I think the actual behavior is nice and is also how it works on the main Kiwi.com website. Hiding the search button on results seems a simpler idea...

**Comment by FilipMessa** [comment]
OK then definitely will be better just hide search button
