### ISSUE TITLE
BUG: Styles blinking 

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#80]
After upgrade to `react-native-web@0.9.9` styles blinking appears when the first page render.
And also there is the error msg in the terminal. ``` Invalid style with id `178`. Skipping ...```

<img width="584" alt="screen shot 2018-12-19 at 17 37 28" src="https://user-images.githubusercontent.com/6354326/50234308-aa249980-03b5-11e9-9544-621774efd12c.png">

<img width="1680" alt="screen shot 2018-12-19 at 17 37 49" src="https://user-images.githubusercontent.com/6354326/50234221-747fb080-03b5-11e9-8ad4-94e0446d6276.png">

**Comment by JoseDuSV** [comment]
I've been playing with this a bit while working on Search form design. And realised that beside blinking and console warnings there is also whole `NavBar` (below) missing in recent version and scrolling on results list stopped working.

<img width="430" alt="screenshot 2018-12-20 at 18 30 11" src="https://user-images.githubusercontent.com/2660330/50301267-25a24b80-0487-11e9-8eef-b97286aa2616.png">

But while trying rolling back to old version and then returning to recent 0.9.9 everything started to work as before and even warnings are gone.

Can somebody else please try to remove `node_modules` folder and run clean `yarn install` to see if it helps? Thanks

**Comment by JoseDuSV** [comment]
Can confirm that deleting `node_modules` + `yarn.lock` works for me.
The problem sometimes return when I switch between branches. But fresh modules installation works every time.
It seems like some problem between dependencies versions.
Maybe creating fresh `yarn.lock` for master can help.

**Comment by FilipMessa** [comment]
Thanks, @JoseDuSV.
I followed your steps and it works. So let's try to create new yarn.lock.
