### ISSUE TITLE
Change Slider's label when user select only one value in range type

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#807]
Current state

<img width="363" alt="Screenshot 2019-05-22 at 09 45 29" src="https://user-images.githubusercontent.com/858321/58156433-5c6ad080-7c76-11e9-898e-913b72cafaa9.png">

Desired state:

![57614305-27c18f80-7579-11e9-8564-53cd9d02760d](https://user-images.githubusercontent.com/858321/58156277-06962880-7c76-11e9-8e38-7192550719fd.gif)

**Waiting for #762**

**Comment by RobinCsl** [comment]
@JoseDuSV regarding this comment https://github.com/kiwicom/margarita/pull/761/files#r283279629

where can I find the implementation of this (more functional) slider?

**Comment by JoseDuSV** [comment]
> @JoseDuSV regarding this comment https://github.com/kiwicom/margarita/pull/761/files#r283279629
> 
> where can I find the implementation of this (more functional) slider?

@RobinCsl I think it was recorded directly on https://www.kiwi.com/en/ in `Trip length` section https://monosnap.com/file/MN1F8qijcEI9Wby2JUP0TsWFQQwpEJ . Sadly it is some custom implementation inside `Search` repo (search for `DoubleSlider`) so it's not easily reusable.
