### ISSUE TITLE
Investigate random failing of CircleCI tests

### ISSUE THREAD

**Issue by JoseDuSV** [kiwicom/margarita#82]
As observed on multiple pull requests, **CircleCI** tests seems to be randomly failing from time to time without any error within code.

Few repeating examples:
https://circleci.com/gh/kiwicom/margarita/186
https://circleci.com/gh/kiwicom/margarita/183
https://circleci.com/gh/kiwicom/margarita/162

**Comment by RobinCsl** [comment]
Hopefully that PR will improve things #86. Closing for now.
