### ISSUE TITLE
BUG: As a user, I can't find the Dublin city in location picker

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/margarita#824]
When I tried to search for the Dublin, the `We couldn't find what you were looking for` message appears.

Steps:
1. open location picker
2. write Dublin
3. no results

When I checked the graphql console I saw this error

<img width="673" alt="Screen Shot 2019-05-27 at 10 06 43" src="https://user-images.githubusercontent.com/6354326/58405452-bbaa5580-8067-11e9-9903-f0c166032d28.png">

**Comment by KarinaDavtyan** [comment]
I got the same or similar when I was searching for Malaga. Appeared that it spelled like M*á*laga and I didnt even know about it before (lived there for 3-4 years 😅)
And the search didnt give any suggestions
