### ISSUE TITLE
Add possibility of choosing year in the new Range Date Picker

### ISSUE THREAD

**Issue by KarinaDavtyan** [kiwicom/margarita#829]
It would be needed for choosing date of birth

**Comment by FilipMessa** [comment]
I am not sure if RangePicker is a good idea to use the RangePicker for passengers.
From my point of view, it is a difrent use case

**Comment by KarinaDavtyan** [comment]
Its totally different 
*Web*
![Screenshot 2019-05-27 at 12 37 19](https://user-images.githubusercontent.com/25099820/58414627-41d09700-807c-11e9-8fdf-f027006fec65.png)

*Mobile*
![Image from iOS (5)](https://user-images.githubusercontent.com/25099820/58414692-72b0cc00-807c-11e9-8204-2ab95ca6adea.png)

**Comment by KarinaDavtyan** [comment]
![Screenshot 2019-05-27 at 11 46 55](https://user-images.githubusercontent.com/25099820/58414748-a3910100-807c-11e9-84c6-9182cb14bb8d.png)
And this is what we have now, so I think it should be replaced. if not with new Range date picker but with web implementation from kiwi.com at least

**Comment by FilipMessa** [comment]
@jvaclavik What do you think about that?

**Comment by jvaclavik** [comment]
Maybe there shouldn't be any calendar-like date picker for this. Select for days/months/years should be totally enough and on mobile I would keep it native as in screenshots from @KarinaDavtyan.

If we want to have there a calendar, according to me it should be consistent with `RangeDatePicker` 
but it should be possible to go across the years and months. 

Right now it's terrible to find your birth date when I have to click maybe even hundred times.

**Comment by FilipMessa** [comment]
OK, I understand what option you vote for?

1. Select for days/months/years and native on mobile
2. Improve the RangePicker

**Comment by FilipMessa** [comment]
Anyway it looks like that the 1 option will be the easiest way, how to improve UX

**Comment by KarinaDavtyan** [comment]
Agree, lets go with a 1st option

**Comment by KarinaDavtyan** [comment]
@FilipMessa should we close this issue and 2 others I opened (#828, #830) And then open 2 more, 1 for mobile version and 1 for web (1st option)?

**Comment by FilipMessa** [comment]
@KarinaDavtyan sounds good sorry for the delay
