### ISSUE TITLE
[LandingPage] Page is not displayed properly

### ISSUE THREAD

**Issue by KarinaDavtyan** [kiwicom/margarita#843]
- The medium font (Circular Pro) is not loaded

Firefox - works as expected
<img width="433" alt="Screenshot 2019-05-28 at 13 21 04" src="https://user-images.githubusercontent.com/25099820/58474467-7b240800-814b-11e9-8b4f-e6aa62a95e08.png">
Chrome - does not work
<img width="447" alt="Screenshot 2019-05-28 at 13 22 18" src="https://user-images.githubusercontent.com/25099820/58474543-b8889580-814b-11e9-84c0-e723175996a1.png">
Safari - does not work
<img width="418" alt="Screenshot 2019-05-28 at 13 23 51" src="https://user-images.githubusercontent.com/25099820/58474597-ebcb2480-814b-11e9-9d34-d051a720b472.png">

- Floating phone on the right side are not loaded in any of the checked browsers (Chrome, Firefox, Safari)

<img width="1438" alt="Screenshot 2019-05-28 at 13 27 37" src="https://user-images.githubusercontent.com/25099820/58474769-685e0300-814c-11e9-946c-083c17053c35.png">

1. Go to https://margarita.kiwi.com/

**Comment by KarinaDavtyan** [comment]
It has recovered itself in the same day. Requires further investigation, in case of occurring again

**Comment by jvaclavik** [comment]
I think we can close it for now, what do you think @KarinaDavtyan?
