### ISSUE TITLE
Scrolling is clicking in results on web version with using mobile device

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#891]
![ezgif com-optimize (9)](https://user-images.githubusercontent.com/858321/59591700-c39d6880-90ee-11e9-8a21-730bc975fe83.gif)

**Comment by RobinCsl** [comment]
I believe that's only on Chrome on Desktop; the attached GIF is on Chrome on my device.

Note however that the scrollview is way too small on small screens.


![example](https://user-images.githubusercontent.com/22741774/60973874-55cd1100-a329-11e9-8c0d-34cf29fd3b4b.gif)
