### ISSUE TITLE
Add loader text during opening PlacePicker modal

### ISSUE THREAD

**Issue by jvaclavik** [kiwicom/margarita#907]
Add `Locations are loading...` here:
<img width="794" alt="Screenshot 2019-06-25 at 16 57 57" src="https://user-images.githubusercontent.com/858321/60109368-85e1b500-976a-11e9-88e0-56f553d48cb4.png">

**Comment by KarinaDavtyan** [comment]
What about also adding https://images.kiwi.com/illustrations/originals/OpenSearch.png or https://images.kiwi.com/illustrations/originals/DesktopSearch.png ?

**Comment by jvaclavik** [comment]
> What about also adding https://images.kiwi.com/illustrations/originals/OpenSearch.png or https://images.kiwi.com/illustrations/originals/DesktopSearch.png ?

It could be also there, but definitely with the text
