### ISSUE TITLE
install the margarita in my domain

### ISSUE THREAD

**Issue by addynb** [kiwicom/margarita#918]
How can install the margarita in my domain, some tutorial to newbie?

**Comment by wingdu** [comment]
that is a good question, i have use the documentation here and its doesnt work really..

**Comment by FilipMessa** [comment]
Hi, all this project is frozen, no devs are currently assigned on that.
The plan is to continue on that at some point but no time for that right now

**Comment by Atasflame** [comment]
Please do it ASAP, we are waiting! How install the Margarita to domain!!! Thanks

**Comment by TobbyReign** [comment]
> 
> 
> Please do it ASAP, we are waiting! How install the Margarita to domain!!! Thanks

Wow, is that serious ?

**Comment by RobinCsl** [comment]
I will archive the repository since there are no current plans to maintain it.

Thanks again for your interest in Margarita!
