### ISSUE TITLE
[General Enquiry] 

### ISSUE THREAD

**Issue by wingdu** [kiwicom/margarita#919]
Hey Guys,

i find the documentation about it a little but pure.. its possible to get a better one ?

**Comment by wingdu** [comment]
git clone https://github.com/kiwicom/margarita
cd margarita/
yarn

00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

**Comment by FilipMessa** [comment]
Hi @wingdu, this project is frozen, no devs are currently assigned on that.
The plan is to continue on that at some point but no time for that right now.

I don't know but maybe you run on wrong node version try to use the v11.15.0 version.

**Comment by wingdu** [comment]
can you please explain me that detailed ? 

i have check it out, then i go to the maragirta folder and then i start yarn and it do nothing .. honestly.. or i have to run node ? and then yarn ?

**Comment by wingdu** [comment]
i have found the issue :-)
