### ISSUE TITLE
[General Enquiry] Tequila API quota increase

### ISSUE THREAD

**Issue by itsmeshreyans** [kiwicom/margarita#941]
Hello,

We are using the Tequila multi city search api and we were wondering if there was a way to increase the per minute quota?

Thank you,
Shreyans Bhansali

**Comment by RobinCsl** [comment]
Hello Shreyans,

I would encourage you to reach the Tequila support directly.

I will archive the repository since there are no current plans to maintain it.

Thank you for your understanding.
